# -*- coding: utf-8 -*-
"""Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1br_mCyp0Idi4RY2RN6ysXvQ9FHCVNs34

**Program To Print Calendar**
"""

import calendar
yy = 2025 #year
mm=10  #month
print(calendar.month(yy,mm))

"""**Print Hello World**"""

print("Hello Yash!! ")

Monday=98 # Attendance of monday
Tuesday=90 # Tuesday Attendance
avg=(Monday+Tuesday)/2
print(avg)

"""Python is Case Sensitive ✅"""

name ="Abhinav"
Name="Awasthi"
print(name)
print(Name)

"""**Operator**"""

print(3+3) # Addition
print(100-20) # substraction
print(20*10) #Multiplication
print(600/2) # Division
print(500//6) # Floor Div
print(34%3) # Modulo
print(2**3) # Exponential

a=10
print(a)
a+=2
print(a)
a-=2
print(a)
a*=9
print(a)

age=10
height=12.45
print(age,type(age))
print(height,type(height))

s1="Yash"
print(s1,type(s1))

"""**I/p & O/p**"""

First_Name=input("Enter First Name")
Last_Name=input("Enter Last Name")
print(First_Name,Last_Name)

age= int(input())
height= float(input())
print(age,height)

"""**Control Statements**

"""

# Take input of age to check weather age is eligible for driving licence or Not
age = int(input("Enter the Age"))
if(age>=18):
  print("Eligible For Drive")
else:
   print("Not eligible to Drive")

marks = int(input("Enter the Marks: "))
if(marks>=90):
   print("Excellent")
elif(marks>=70):
  print("Good")
elif(marks>=40):
  print("Fair")
else:
    print("Bad")

temp=int(input("Enter the Tempreture"))
if(temp<=50) and (temp>=25):
  print("Hot")
elif( temp<=24) and (temp>=10):
   print("Cold")
else:
    print("Extremly Cold")

# Ternary Operator
age = int(input())
result = "Eligible" if age>=18 else "Not eligible"
print(result)

# While Loop
i=0
while(i<5):
  print(i,end=" ")
  i+=1

# For Loop
list1 = [3,3,5,2,1]

for i in list1:
  print(i,end=" ")

for i in range(1,11):
  print(i,end=" ")
print()

for i in range(5,11):
  print(i,end=" ")
print()

for i in range(1,11,2):
  print(i,end=" ")
print()

for i in range(20,0,-1):
  print(i,end=" ")
print()

for i in range(20,0,-3):
  print(i,end=" ")
print()

# Function
def printName(name):
  print(name)

printName("Abhinav Awasthi")

def addTwoNumbers(a,b):
  sum = a+b
  return sum

ans = addTwoNumbers(4,7)
print(ans)